// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANlvnqWuYekUMY6fSTrUGN_lIAyo_SkU8',
    appId: '1:344464695437:web:b9b361844c23a024d4c2c4',
    messagingSenderId: '344464695437',
    projectId: 'newportfolio-16a51',
    authDomain: 'newportfolio-16a51.firebaseapp.com',
    storageBucket: 'newportfolio-16a51.appspot.com',
    measurementId: 'G-G1NYZ1GMM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7pfa7WTbD0ZhK8aktuULhvG-Plw_ii0',
    appId: '1:344464695437:android:907940a6e738a09dd4c2c4',
    messagingSenderId: '344464695437',
    projectId: 'newportfolio-16a51',
    storageBucket: 'newportfolio-16a51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx4zhnYvj2VkIjUJ-nHeoWHN-KAZxa4oQ',
    appId: '1:344464695437:ios:3c91f55602038bb7d4c2c4',
    messagingSenderId: '344464695437',
    projectId: 'newportfolio-16a51',
    storageBucket: 'newportfolio-16a51.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx4zhnYvj2VkIjUJ-nHeoWHN-KAZxa4oQ',
    appId: '1:344464695437:ios:709f83023a603a9bd4c2c4',
    messagingSenderId: '344464695437',
    projectId: 'newportfolio-16a51',
    storageBucket: 'newportfolio-16a51.appspot.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
